### ISSUE TITLE
Preventing the proliferation of file name patterns

### ISSUE THREAD

**Issue by DamienIrving** [CWSL/cwsl-mas#21]
Consider the following workflow, which plots the Southern Hemisphere Rossby Wave Source (RWS) climatology:
* Get CMIP5 zonal (u) and meridional (v) wind data (i.e. the `constraint builder`, `CMIP5` and `merge timeseries` modules in VisTrails)
* Select the 500hPa level (`cdo sellevel`)
* Calculate the RWS (`calc_rws.py`; requires u and v wind as input)
* Select 1981-2000 period (`timeslice` module)
* Calculate climatology (`climatology` module)
* Plot Southern Hemisphere (`plot_map.py`)

The first and last steps in this process are fixed (i.e. get the data first and plot the output last) but the other 4 steps could conceivably be performed in any order (i.e. 4! = 24 possibilities). As it stands, each one of these possibilities would require a different file name pattern in `pattern_generator.py` (e.g. if the u and v climatology were calculated prior to calculating the RWS, the `%seas_agg%` constraint would be introduced into the pattern much earlier on). The base data could also be either daily or monthly timescale (there are non-linearities in the calculation of the RWS so you get a different climatology depending on whether you start with daily or monthly data) and the Southern Hemisphere region could be extracted early on to reduce the amount of data processing, adding even more possible combinations. I guess the point I'm making is that we need to come up with a strategy for avoiding the uncontrolled proliferation of file name patterns. Instead, we should be aiming to get to the point where defining a new path is something that very rarely needs to be done. Here's my thoughts on how we could do that:

### 1. Specify a preferred order of operations

The first thing we could do to reduce the number of possible module combinations would be to define a preferred order of operations (e.g. like BODMAS in mathematics). In general, we'd like people calculate their new variable first (e.g. for the entire global grid) so that others who are interested in different regions don't have to re-calculate it. Next people should crop their data (e.g. select a time period or spatial region), then do any temporal or spatial aggregation (e.g. climatology, zonal mean), then finally do whatever else is left (calculate an index, plot). So the order might be:
1. Variable 
2. Crop (temporal then spatial) 
3. Aggregate (temporal then spatial) 
4. Calculate your index or whatever else you need to do 

### 2. Placeholder constraints

Every workflow begins with a file that looks something like this:
`%variable% _ %mip_table% _ %model% _ %experiment% _ %ensemble% . %suffix%`

If this pattern came with a bunch of placeholder constraints, the current task of defining a new pattern would in many cases be replaced by a simple update to the relevant placeholder. For example, if every workflow started like this:
`%variable% _ %mip_table% _ %model% _ %experiment% _ %ensemble% _ %lon_bounds% _ %lat_bounds% _ %vertical_bounds% _ %time_bounds% _ %grid% . %suffix%`

Then the initial/default placeholders could be something like:
* `%lat_bounds%` = `%south_lat%to%north_lat%-%lat_agg%` (default might be `-90to90-no-agg`)
* `%lon_bounds%` = `%west_lon%to%east_lon%-%lon_agg%` (e.g. `0to360-zonalmean`)
* `%vertical_bounds%` = `%bottom_level%to%top_level%-%vertical_agg%` (default might be `0to1000hPa-no-agg`)
* `%time_bounds%` = `%start_time%to%end_time%-%time-agg%` (e.g. `1979-01-01to1990-12-31-runmean30`) 
* `%grid%` (default might be `native`)

Performing a task like seasonal aggregation would then not require a new pattern, you would simply update the `%grid%` to be `r240x120` instead of `native`.

### 3. Avoiding redundancy

While placeholder constraints remove the need for a new pattern every time you crop the data or change timescale or grid, they don't cover all eventualities and they could lead to a lot of redundant information in the file name. A strategy for tackling this problem is discussed in #24 .
 
### 4. Optional archiving of intermediate files

Perhaps we should make the archiving of intermediate files optional? For workflows that can be re-executed very quickly or ones where the researcher isn't writing their output to the shared data repository on `/g/data/`, we don't really care if the intermediate files created during the workflow are kept (i.e. it might be ok just to keep the final .png file and not all the .nc files created along the way). By extension, we don't care what the intermediate file name patterns are.

**Comment by captainceramic** [comment]
Good idea - introducing a pattern that will cover almost all of the outputs makes things much easier.

For your point 4, the existing code already does this - the `FileCreator.default_pattern` method generates an output file name from the current constraints. A possible approach for this on the VT module side could be to add a drop-down enumeration with a `default pattern | canonical pattern` option, so users can dump their intermediate files to a temporary directory if they want.

**Comment by DamienIrving** [comment]
@taerwin also suggested that it would be nice if the user could override the output file pattern if they want

**Comment by DamienIrving** [comment]
@captainceramic @taerwin In order to initialise my placeholder constraints (i.e. I need to figure out what the initial latitude, longitude, level and time bounds are), I was thinking about making some additions to [`version_safe_cdscan.py`](https://github.com/CWSL/cwsl-ctools/blob/master/aggregation/version_safe_cdscan.py). That script is called at the "merge timeseries" point in any workflow and is really the first point where the constraints can differ from those defined by the CMIP5 directory reference syntax. Within `version_safe_cdscan.py` I was thinking I could simply interrogate the `cdms2.dataset.CdmsFile` object and ask for it's axis bounds (cdat is nice because you don't have to read in the data in order to find out information like this).

My question is, how do I get that new constraint information from `version_safe_cdscan.py` to the next step in the workflow?

**Comment by DamienIrving** [comment]
Once I've been able to initialise the constraints, I'm thinking I'd like to have a go at changing the way patterns are generated. At the moment you give [`pattern_generator.py`](https://github.com/CWSL/cwsl-mas/blob/master/cwsl/core/pattern_generator.py) a data type (e.g. `monthly_ts` or `seasonal_indices`) and it picks the predefined pattern. I'm thinking it would be better if the process was more dynamic than that. You should be able to give `pattern_generator.py` your list of output constraints and it then figures out what the appropriate pattern should be.

**Comment by captainceramic** [comment]
@DamienIrving - regarding your question about getting metadata from files then creating constraints from them: I haven't thought about doing this before, but it is a good idea.

The ease in doing it will depend a little on whether the metadata elements (lat and lon bounds etc) are the same for each file or not.

If they are the same for every file in every input `DataSet`, then I think a process could be done from the `compute` method of a VisTrails module:
1. Using the `.files` property of the input, grab the name of one input file.
2. Run a `subprocess` or a function (a subprocess might be easier because you can control the execution environment) that generates the information you need.
3. Create your new `Constraints` from that new information and pass them in to the `ProcessUnit` before execution.

There could certainly be other ways to do it as well.

A down side to this process is that it puts a lot of code into the VisTrails module, rather than it just being a thin wrapper. This makes it harder to unit test. That seems like a fair trade off for the functionality though.

If the metadata was different for every file you would have to do it slightly differently - probably performing a similar process for each file in the input could work, then adding the new `Constraint` for each file. This would require a bit more work though.

More generally, I think that there is a bit of a risk using the `cdscan` and cdat catalogue approach for general workflows. They may be the best tool for now, but I am concerned that they may fall over when using the big daily oceanographic files that Jaci requires. I would certainly test it first and chat to @taerwin about if there are other directions CSIRO want to go.

I've created a new issue for your other suggestion regarding `pattern_generator.py`.

**Comment by DamienIrving** [comment]
Ah, ok. So I wouldn't make the changes in `version_safe_cdscan.py` but rather the wrapper `vt_cdscan.py` - that makes sense. I agree that in general we don't want to be doing so much work within the wrapper, but I think `vt_cdscan.py` is a special case that we could make an exception for. I'll have a try and see how I go - while every file within a `DataSet` will probably have the same latitude and longitude bounds (i.e. the whole globe) they will not have the same time or level bounds.

**Comment by captainceramic** [comment]
This new system using a single pattern for all operations seems to be working quite well, so I am closing this up for the moment. We can re-open if the scheme needs revisiting.
