### ISSUE TITLE
The ability to automatically determine the correct pattern from a set of `Constraints`

### ISSUE THREAD

**Issue by captainceramic** [CWSL/cwsl-mas#24]
@DamienIrving has suggested an enhancement, introducing the ability to map straight from a set of `Constraints` to the correct output pattern.

There was a bit of history with the existing `PatternGenerator` class - older VT modules for the plugin would usually take in a plain string format pattern into a port - something like:
`"/this/is/%a%/%really%/%long%/%pattern%/%which%/%is%/%a%/%hassle%_%to%_%type%"`, which was difficult and error-prone to enter through the GUI.

To deal with that, we made a VT module to handle the complexity, with the idea that the user would select the 'category' (`season_indices`) etc, then the VT module would output the correct pattern as a string. This meant that if a user wanted to write their own pattern they still could - they could disconnect the VT module and type their pattern in.

From there, the thinking was that since the patterns were so complex and there was only one possible choice per process, it was better to move the pattern generation inside the process VT modules and pull in some information from the user's module configuration.

I think the idea of simplifying the link between constraint names and patterns is a good one.

**Comment by DamienIrving** [comment]
I think this ability to map straight from a set of `Constraints` to the correct pattern would help immensely in solving #21 . For example, let's say the template file pattern for specifying the longitude bounds is `%west_lon%-%east_lon%-%lon-agg%`. If no aggregation has been done, you'd just have to set `%lon-agg%` to a default value like `no-agg`. If you only select a single longitude, you'd also have to set both `%east_lon%` and `%west_lon%` to the same value, adding more redundant information to your file name. Repeat for latitude, level and time and all of a sudden you've got lots of redundant information in your file name. 

By mapping the `Constraints` straight to a pattern you could have series of conditional statements that would decide (for example) that in the case of a single longitude and no longitude aggregation, the whole longitude bounds part of the pattern could just be represented by a single number.

**Comment by DamienIrving** [comment]
Come to think of it, maybe we don't need to initialise constraints (e.g. like `no-agg`) at all? By default, it could just be that information about bounds or aggregation (i.e. data processing) wouldn't appear in the constraint list (and hence the file pattern) until it had been modified from the downloaded state (e.g. the longitude bounds wouldn't appear in the constraint list or file pattern until either subsetting or aggregation was applied along that axis).

This approach is much more consistent with how the constrains are currently handled, which means there would be only one major hurdle to mapping straight from a set of constraints to the correct output pattern (i.e. we would avoid the issues associated with getting metadata from files to initialise constraints, as discussed in #21 ). That hurdle is that as is stands the initial constraints for the output are built from the output file pattern (see line 85 of `process_unit.py`). We need it to be the other way around - the output file pattern gets built from the constraints.

**Comment by captainceramic** [comment]
Using the new, single-pattern approach seems to be working well for now. We can revisit this if it becomes necessary in the future.
