### ISSUE TITLE
Module Documentation

### ISSUE THREAD

**Issue by jimjam-slam** [CWSL/cwsl-mas#48]
Hi guys, just wondering if there's any documentation on the individual modules beyond that found when clicking the 'Documentation' button on VisTrail's module pane. I'm having a hard time assessing whether the modules available could meet my needs or whether I need to write a new one. Cheers!

**Comment by DamienIrving** [comment]
@rensa  If you want to know more about the individual modules, the source code for all them lives in the cwsl-ctools repo:
https://github.com/CWSL/cwsl-ctools

Many of the modules will tell you which script in that repo they are based on (e.g. it will say something like "wraps the cwsl-ctools/aggregation/cdo_ensemble_agg.sh script" when you click the documentation button), but if they don't then you'll need to work backwards from the [init.py](https://github.com/CWSL/cwsl-mas/blob/master/cwsl/init.py) file. At the top of that file you'll see something like `from cwsl.vt_modules.vt_field_agg import FieldAggregation`, which means the VisTralis module file for `FieldAggregation` is located at [cwsl-mas/cwsl/vt_modules/vt_field_agg.py](https://github.com/CWSL/cwsl-mas/blob/master/cwsl/vt_modules/vt_field_agg.py). In that file you'll see a reference to a script in the cwsl-ctools repo.

Hope that makes sense!

**Comment by jimjam-slam** [comment]
Thanks @DamienIrving! I'll take a couple apart and see if I can get a better feel for them :)
