### ISSUE TITLE
Using multiple attributes of a dataset as a single argument

### ISSUE THREAD

**Issue by taerwin** [CWSL/cwsl-mas#7]
Example plot heading which includes model and variable name,

i.e --title="%model% %experiment%"   ->   --title="ACCESS1-0 rcp45"

**Comment by captainceramic** [comment]
This has been implemented as an addition to the `ProcessUnit` API - the syntax is `kw_string="--title ${model} ${experiment}"`

See commit 4bec77fac1f7b3d8646e4d6b49f2bf3df6098af4
